# Generated by Django 5.0.6 on 2024-06-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductmodel',
            name='warehouse_product_description',
            field=models.TextField(default='Test Description', max_length=355),
            preserve_default=False,
        ),
    ]
