# Generated by Django 5.0.6 on 2024-09-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicerequestmodel',
            name='sale_amount',
        ),
    ]
