# Generated by Django 5.0.6 on 2024-09-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_invoicerequestmodel_sale_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
