# Generated by Django 5.0.6 on 2024-06-08 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_warehouseproductmodel_warehouse_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('categogry_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=255)),
                ('category_date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='warehouseproductmodel',
            name='warehouse_product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.categorymodel'),
        ),
    ]
