# Generated by Django 5.0.6 on 2024-07-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_categorymodel_options_salemodel_encoded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='sale_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
