# Generated by Django 5.0.6 on 2024-07-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_salemodel_sale_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceModel',
        ),
    ]
