# Generated by Django 5.0.6 on 2024-07-08 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_warehouseproductmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemodel',
            name='sale_date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
