# Generated by Django 5.0.6 on 2024-07-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_salemodel_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.TextField(choices=[('Cashier', 'Cashier'), ('Attendant', 'Attendant'), ('Manager', 'Manager')], default='Cashier'),
        ),
    ]
