# Generated by Django 5.0.6 on 2024-07-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_warehouseproductmodel_warehouse_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
