# Generated by Django 5.0.6 on 2024-09-22 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_requestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='request_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.salemodel'),
        ),
    ]
